{{- if .Values.deployment.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        type: deployment
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: docker-sock
        hostPath:
         path: /var/run/docker.sock
      - name: dev-vol
        hostPath:
         path: /dev
      - name: proc-vol
        hostPath:
         path: /proc
      - name: boot-vol
        hostPath:
         path: /boot
      - name: modules-vol
        hostPath:
         path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
          privileged: true
        env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: access-key
          - name: TAGS
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: tags
{{- $additionalconf := .Values.sysdig.AdditionalConf -}}
{{- if .Values.secure.enable }}
{{- $additionalconf := printf "%s%s" .Values.secure.SecureConf .Values.sysdig.AdditionalConf -}}
{{- end }}
          - name: ADDITIONAL_CONF
            value: {{ $additionalconf | quote }}
{{- if .Values.sysdig.env }}
{{ toYaml .Values.sysdig.env | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
{{- end -}}