# Default values for Sysdig Monitor and Secure Helm package.

rbac:
    # true here enables creation of rbac resources
    install: false
    # rbac version
    apiVersion: v1beta1

image:
    repository: "sysdig/agent"
    tag: "latest"
    pullPolicy: "Always"

sysdig:
    # Required: You need your Sysdig Monitor access key before running agents.
    # AccessKey: ""

    # Optional: Key-value agent tags following the format "key:val,key2:val2".
    AgentTags: ""

    # Optional: additional configuration parameters.
    # This will be moved into a ConfigMap shortly.
    AdditionalConf: "\nstatsd:\n  enabled: false\njmx:\n  enabled: false\napp_checks:\n  - name: postgres\n    pattern:\n      port: 5432\n      comm: postgres\n    conf:\n      username: concourse\n      password: concourse\n      host: 10.1.48.60\n      port: 5432\n      dbname: concourse\nlog:\n  file_priority: debug\n"
    
#    AdditionalConf: "\nstatsd:\n  enabled: false\njmx:\n  enabled: false\napp_checks:\n  - name: postgresql\n    pattern:\n      port: 5432\n      comm: postgres\n    conf:\n      username: concourse\n      password: concourse\n      host: 10.1.48.60\nlog:\n  file_priority: debug\n"

    #"\napp_checks_enabled: true\napp_checks:\n  - name: postgresql\n    pattern:\n      port: 5432\n      comm: postgres\n    conf:\n      username: postgres\n      host: 10.1.48.60\nlog:\n  file_priority: debug"

    serviceAccountName: "sysdig-account"

    # Optional: array of additional env variables used for custom config.
    # env:
    #   - name:
    #     value:

daemonset:
    enabled: false

deployment:
    enabled: true
    replicas: 1

#    service:
#        enabled: true
#        type: ClusterIP

secure:
    # true here enables Sysdig Secure: container run-time security & forensics
    enable: false

    # Default Sysdig Secure configuration (please add trailing \n)
    SecureConf: "security: {enabled: true}\ncommandlines_capture: {enabled: true}\nmemdump: {enabled: true}\n"

resources:
    requests:
        cpu: 100m
        memory: 512Mi
    limits:
        cpu: 500m
        memory: 768Mi

# Allow sysdig to run on Kubernetes 1.6 masters.
tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
